variable "subnet_id" {}
variable "vpc_security_group_ids" {}
variable "key_name" {}
variable "instance_type" {}
variable "ami" {}
variable "tags" {}
variable "instance_count" {}
variable "install_package" {}
variable "playbook_name" {}
